# Generated by Django 5.1.2 on 2024-11-11 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "css",
                    models.CharField(
                        choices=[
                            ("btn-primary", "Primary"),
                            ("btn-secondary", "Secondary"),
                            ("btn-success", "Success"),
                            ("btn-danger", "Danger"),
                            ("btn-warning", "Warning"),
                            ("btn-info", "Infomation"),
                            ("btn-light", "Light"),
                            ("btn-dark", "Dark"),
                            ("btn-link", "Link"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
            options={
                "verbose_name": "Status",
                "verbose_name_plural": "Status",
                "db_table": "status",
            },
        ),
        migrations.CreateModel(
            name="PersonStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nightly_reset", models.BooleanField(default=False)),
                ("notes", models.CharField(max_length=100)),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="StatusBoard.status",
                    ),
                ),
            ],
            options={
                "verbose_name": "PersonStatus",
                "verbose_name_plural": "PersonStatus",
                "db_table": "person_status",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(blank=True, max_length=100)),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="member_of", to="StatusBoard.personstatus"
                    ),
                ),
                (
                    "mods",
                    models.ManyToManyField(
                        related_name="moderating", to="StatusBoard.personstatus"
                    ),
                ),
            ],
        ),
    ]
