# Generated by Django 5.1.2 on 2024-10-27 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Roster", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="affiliation",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Roster.affiliation",
            ),
        ),
    ]
