# Generated by Django 5.1.2 on 2024-10-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Roster", "0003_alter_person_affiliation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.CharField(
                error_messages={
                    "unique": "A user with that email address already exists"
                },
                help_text="Required",
                max_length=50,
            ),
        ),
    ]
