# Generated by Django 5.1.2 on 2024-11-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Roster", "0004_alter_person_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="middle_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
