# Generated by Django 5.1.2 on 2024-11-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Roster", "0007_alter_profile_home_phone_alter_profile_mobile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="home_phone",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="mobile_phone",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
