# Generated by Django 5.1.2 on 2024-11-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Roster", "0008_alter_profile_home_phone_alter_profile_mobile_phone"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
