# Generated by Django 5.1.7 on 2025-03-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Roster", "0009_delete_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
