# Generated by Django 5.2.4 on 2025-07-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StatusApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="member_of", to="StatusApp.userstatus"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="mods",
            field=models.ManyToManyField(
                blank=True, related_name="moderating", to="StatusApp.userstatus"
            ),
        ),
    ]
