# Generated by Django 5.2.4 on 2025-07-15 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("StatusApp", "0002_alter_group_members_alter_group_mods"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userstatus",
            old_name="User",
            new_name="user",
        ),
    ]
