# Generated by Django 5.2.4 on 2025-07-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StatusApp", "0003_rename_user_userstatus_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstatus",
            name="notes",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
