# Generated by Django 5.2.4 on 2025-07-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StatusApp", "0004_alter_userstatus_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstatus",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
