# Generated by Django 5.2.4 on 2025-07-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StatusApp", "0005_userstatus_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstatus",
            name="reset_notes",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userstatus",
            name="nightly_reset",
            field=models.BooleanField(default=True),
        ),
    ]
