# Generated by Django 5.2.4 on 2025-07-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StatusApp", "0006_userstatus_reset_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userstatus",
            name="nightly_reset",
        ),
        migrations.AddField(
            model_name="userstatus",
            name="reset_status",
            field=models.BooleanField(default=False),
        ),
    ]
