# Generated by Django 5.2.4 on 2025-07-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StatusApp", "0007_remove_userstatus_nightly_reset_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userstatus",
            old_name="reset_notes",
            new_name="lock_notes",
        ),
        migrations.RemoveField(
            model_name="userstatus",
            name="reset_status",
        ),
        migrations.AddField(
            model_name="userstatus",
            name="lock_status",
            field=models.BooleanField(default=True),
        ),
    ]
