# Generated by Django 5.2.4 on 2025-07-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StatusApp", "0008_rename_reset_notes_userstatus_lock_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstatus",
            name="lock_status",
            field=models.BooleanField(default=False),
        ),
    ]
